version: '3.8'

services:
  # Python container
  try_docker_py:
    build:
      context: .
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
    ports:
      - "5555:5555"
    volumes:
      - ./app:/app

  # MySQL container
  try_docker_sql:
    container_name: try_docker_sql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: lenochka
      MYSQL_PASSWORD: lenochka
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql